### ISSUE TITLE
unable to bootstrap branch protection for a branch

### ISSUE THREAD

**Issue by mattsb42** [mattsb42/repo-admin#54]
Attempting to bootstrap branch protection fails because when repo-manager attempts to find the current  branch protection settings for the branch, it gets a 404 because it does not exist.

```
2020-05-16 19:20:28,261 - MainThread - repo_manager._groups.branches - INFO - Updating branch protection for branch 'development'
2020-05-16 19:20:28,665 - MainThread - repo_manager._groups.branches - WARNING - Branch protection requested for non-existant branch 'development'. Skipping.
Traceback (most recent call last):
  File "/app/build/bin/repo-manager", line 8, in <module>
    sys.exit(cli())
  File "/app/build/repo_manager/__init__.py", line 55, in cli
    apply_config(prepped_config)
  File "/app/build/repo_manager/_groups/__init__.py", line 60, in apply_config
    prepped()
  File "/app/build/repo_manager/_groups/branches.py", line 76, in apply
    raise Exception(f"Encountered unknown error: STATUS {status} :: {current_protection}")
Exception: Encountered unknown error: STATUS 404 :: {'message': 'Branch not protected', 'documentation_url': 'https://developer.github.com/v3/repos/branches/#get-branch-protection'}
```

**Comment by mattsb42** [comment]
The workaround for this is to manually create an empty branch protection rule for that branch and re-run repo-manager.

The fix is that repo-manager needs to understand this failure mode and apply the new branch protection rule.

**Comment by wardsimon** [comment]
As a reference, I've found this to work
```python
import requests

repo = 'xxx'
branches = ['master']
access_token = 'yyy'

for branch in branches:
    r = requests.put(
        'https://api.github.com/repos/{0}/branches/{1}/protection'.format(repo, branch),
        headers={
            'Accept': 'application/vnd.github.luke-cage-preview+json',
            'Authorization': 'Token {0}'.format(access_token)
        },
        json={
            "required_status_checks": {
                'strict': True,
                'contexts': []
            },
            "enforce_admins": True,
            "required_pull_request_reviews": {
                # 'Only organization repositories can have users and team restrictions'
                # 'dismissal_restrictions': {
                #     'users': [],
                #     'teams': []
                # },
                'dismiss_stale_reviews': False,
                'require_code_owner_reviews': True,
                'required_approving_review_count': 1
            },
            # 'Only organization repositories can have users and team restrictions'
            # "restrictions": {
            #     'users': [],
            #     'teams': [],
            #     'apps': []
            # },
            "restrictions": None,
            'required_linear_history': False,
            'allow_force_pushes': False,
            'allow_deletions': False
        }
    )
    print(r.status_code)
    print(r.json())
```
Maybe this can be a hint

**Comment by mattsb42** [comment]
Thanks. I think what I'll end up doing is just treat 404's as "this needs to be updated", though it'll need to differentiate from "this branch doesn't exist".
